language: java

jdk:
- openjdk8
- oraclejdk8

branches:
  only:
  - master
  - development

before_script: # Perform commands
- cd project
- ls -la

script: # Build the project
- mvn clean package

after_success: # Notify users about the result
- echo “Process terminated successfully”